export enum StoreActionKey {
  SET_NAVIGATION_GROUP = 'SET_NAVIGATION_GROUP',

  SET_ACCOUNT = 'SET_ACCOUNT',
  SET_ACCOUNT_LOADING = 'SET_ACCOUNT_LOADING',

  SELECT_FLIGHT_MESSAGE = 'SELECT_FLIGHT_MESSAGE',

  RESET = 'RESET',

  SET_POST_TYPE = 'SET_POST_TYPE'
}
